app/models.py
from app import db
from datetime import datetime
import re
from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-',s)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    slug = db.Column(db.String(150), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, *args, **kwargs):
        """
        аргументы из конструктора класса Post идут транзитом в класс предок(Model)
        """
        super(Post,self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)

roles_users = db.Table('roles_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
    )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    username = db.Column(db.String(255))
    password = db.Column(db.String(255))
    last_login_at = db.Column(db.DateTime())
    current_login_at = db.Column(db.DateTime())
    last_login_ip = db.Column(db.String(100))
    current_login_ip = db.Column(db.String(100))
    login_count = db.Column(db.Integer)
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    roles = db.relationship('Role', secondary=roles_users,
                         backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

app/app.py
from flask import Flask, redirect,request,url_for
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_admin import AdminIndexView

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_security import SQLAlchemyUserDatastore,Security,current_user




app = Flask(__name__, static_folder='templates/static')
app.config.from_object(Configuration)

db = SQLAlchemy(app)

## Миграции ##
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

## ADMIN ##
from models import *

class AdminMixin:
    def is_accessible(self):
        """
        проверяет доступность действия для пользователя
        """
        return current_user.has_role('admin')

    def inaccessible_callback(self,name, **kwargs):
        return redirect(url_for('security.login', next=request.url))

class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form,model,is_created)

class AdminView(AdminMixin,ModelView):
    """
    переопределяем методы is_accessible, inaccessible_callback из ModelVIew
    """
    pass

class HomeAdminView(AdminMixin,AdminIndexView):
    pass

admin = Admin(app,'FlaskApp',url='/admin',template_mode='bootstrap4',index_view=HomeAdminView(name='Home'))
admin.add_view(AdminView(Post, db.session))

## Flask Security ##
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

app/blog/blueprint.py
from flask import Blueprint, render_template, request
from models import Post

blog = Blueprint('blog', __name__, template_folder='templates')

@blog.route('/')
def index_blog():
    posts = Post.query.all()
    return render_template('blog/blog.html',posts=posts)

@blog.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    return render_template('blog/post_detail.html', post=post)

app/main.py
from app import app,db
from blog.blueprint import blog

import view

app.register_blueprint(blog, url_prefix='/blog')
if __name__ == "__main__":
    app.run()

app/blog/templates/blog/blog.html
{% extends "base.html" %}

{% block title %}
    Блог
{% endblock %}

{% block header_name %}
    Делимся нашими идеями
{% endblock %}

{% block subheader_name %}
    Логика может привести Вас от пункта А к пункту Б, а воображение — куда угодно.
{% endblock %}

{% block content %}
  <!-- START: section -->
  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        {% for post in posts %}
        <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="probootstrap-block-image">
            <figure><img src="{{ url_for('static', filename='img/img_3.jpg') }}" alt="Free Bootstrap Template by ProBootstrap.com"></figure>
            <div class="text">
              <span class="date">{{ post.created }}</span>
              <h3><a href="#">{{ post.title }}</a></h3>
              <p>{{ post.body[:100] }} ...</p>
              <p><a href="{{ url_for('blog.post_detail', slug=post.slug) }}" class="link-with-icon">Читать <i class=" icon-chevron-right"></i></a></p>
            </div>
          </div>
        </div>
        {% endfor %}
        <div class="clearfix visible-sm-block"></div>
      </div>
    </div>
  </section>
  <!-- END: section -->
{% endblock %}

app/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}
    Test
{% endblock %}

{% block header_name %}
    {{ post.title }}
{% endblock %}

{% block subheader_name %}
    Тут будут тэги
{% endblock %}

{% block content %}
  <!-- START: section -->
  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-2 col-md-8 col-sm-6 col-xs-12 probootstrap-animate ">
          <div class="probootstrap-block-image">
            <figure><img src="{{ url_for('static', filename='img/img_3.jpg') }}" alt="postimage"></figure>
            <div class="text">
              <span class="date">{{ post.created }}</span>
              <p>{{ post.body }}</p>
            </div>
          </div>
        </div>
        <div class="clearfix visible-sm-block"></div>
      </div>
    </div>
  </section>
  <!-- END: section -->
{% endblock %}

app/templates/base.html
<!DOCTYPE html>

<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>

      {% block title %}
      {% endblock %} | Супер IT Company

    </title>
    <meta name="description" content="Free Bootstrap Theme by ProBootstrap.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

    {% include 'partials/styles.html' %}

  </head>
  <body>
    
  <!-- START: header -->
  <header role="banner" class="probootstrap-header">

    <div class="container-fluid">
      <!-- <div class="row"> -->
        <a href="#" class="probootstrap-logo">Sublime<span>.</span></a>

        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>

        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            <li><a href="{{ url_for('index') }}">Home</a></li>
            <li><a href="{{ url_for('blog.index_blog') }}">Blog</a></li>
            <li><a href="pricing.html">Pricing</a></li>
            <li><a href="tour.html">Tour</a></li>
            <li><a href="login.html">Log in</a></li>
            <li class="probootstrap-cta"><a href="signup.html">Sign up</a></li>
          </ul>
          <div class="extra-text visible-xs">
            <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
            <h5>Social</h5>
            <ul class="social-buttons">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
            <p><small>&copy; Copyright 2017. All Rights Reserved.</small></p>
          </div>
        </nav>

        <section class="probootstrap-intro">
          <div class="container">
            <div class="row">
              <div class="col-md-8 col-md-offset-2">
                <h1 class="probootstrap-animate">{% block header_name %}{% endblock %}</h1>
                <div class="probootstrap-subtitle probootstrap-animate">
                  <h2>{% block subheader_name %}{% endblock %}</h2>
                </div>
                <p class="watch-intro probootstrap-animate">{% block video_intro %}{% endblock %}</p>
              </div>
            </div>
          </div>
        </section>

      <!-- </div> -->
    </div>

  </header>
  {% block content %}

  {% endblock %}
  
  <!-- START: footer -->
  <footer role="contentinfo" class="probootstrap-footer">

    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="probootstrap-footer-widget">
            <h3>About</h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            <p><a href="#" class="link-with-icon">Learn More <i class=" icon-chevron-right"></i></a></p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="probootstrap-footer-widget">
            <h3>Blog</h3>
            <ul class="probootstrap-blog-list">
              <li>
                <a href="#">
                  <figure><img src="{{ url_for('static',filename='img/img_2.jpg')}}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive"></figure>
                  <div class="text">
                    <h4>River named Duden flows</h4>
                    <p>A small river named Duden flows by their place</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <figure><img src="{{ url_for('static',filename='img/img_3.jpg') }}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive"></figure>
                  <div class="text">
                    <h4>River named Duden flows</h4>
                    <p>A small river named Duden flows by their place</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <figure><img src="{{ url_for('static',filename='img/img_2.jpg') }}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive"></figure>
                  <div class="text">
                    <h4>River named Duden flows</h4>
                    <p>A small river named Duden flows by their place</p>
                  </div>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="probootstrap-footer-widget">
            <h3>Contact</h3>
            <ul class="probootstrap-contact-info">
              <li><i class="icon-location2"></i> <span>198 West 21th Street, Suite 721 New York NY 10016</span></li>
              <li><i class="icon-mail"></i><span>info@domain.com</span></li>
              <li><i class="icon-phone2"></i><span>+123 456 7890</span></li>
            </ul>

          </div>
        </div>
      </div>
      <div class="row mt40">
        <div class="col-md-12 text-center">
          <ul class="probootstrap-footer-social">
            <li><a href=""><i class="icon-twitter"></i></a></li>
            <li><a href=""><i class="icon-facebook"></i></a></li>
            <li><a href=""><i class="icon-instagram2"></i></a></li>
          </ul>
          <p>
            <small>&copy; 2017 <a href="https://probootstrap.com/" target="_blank">ProBootstrap:Sublime</a>. All Rights Reserved. <br> Designed &amp; Developed by <a href="https://probootstrap.com/" target="_blank">ProBootstrap.com</a> Demo Images: Unsplash</small>
          </p>

        </div>
      </div>
    </div>

  </footer>
  <!-- END: footer -->

  {% include 'partials/scripts.html' %}

  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block header_name %}
    РАБОТАЙТЕ С ЛУЧШИМИ
{% endblock %}

{% block subheader_name %}
    Постройте свой бизнес с нами - это просто, быстро и доступно
{% endblock %}

{% block video_intro %}
    <a href="https://vimeo.com/45830194" class="popup-vimeo">Watch the intro <i class="icon-play2"></i></a>
{% endblock %}

{% block content %}
  <!-- END: header -->

  <!-- START: section -->
  <section class="probootstrap-section probootstrap-feature-first">
    <div class="container">
      <div class="row mb70" style="margin-top: -120px;">
        <div class="col-md-4 probootstrap-animate">
          <div class="probootstrap-box">
              <div class="icon"><i class="icon-presentation"></i></div>
              <h3>Business presentation</h3>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
          </div>
        </div>
        <div class="col-md-4 probootstrap-animate">
          <div class="probootstrap-box">
              <div class="icon"><i class="icon-bargraph"></i></div>
              <h3>Business growth</h3>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
          </div>
        </div>
        <div class="col-md-4 probootstrap-animate">
          <div class="probootstrap-box">
              <div class="icon"><i class="icon-megaphone2"></i></div>
              <h3>Standout from the crowd</h3>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-4 probootstrap-animate">
          <p class="text-center">
            <a href="#" class="btn btn-primary btn-lg btn-block" role="button">Get started</a>
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- END: section -->



  <!-- START: section -->
  <section class="probootstrap-section probootstrap-section-extra">
    <div class="container-fluid probootstrap-absolute">
      <div class="row">
        <div class="col-md-7 col-md-push-6 probootstrap-animate" data-animate-effect="fadeInRight">
          <img src="{{ url_for('static', filename='img/img_showcase_2.jpg') }}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive shadow-left">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-md-5 section-heading probootstrap-animate">
          <h2>We guide companies</h2>
          <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>

          <blockquote class="probootstrap-quote">
            <figure class="probootstrap-quote-logo uber">
             <img src="{{ url_for('static',filename='img/uber.png') }}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive">
            </figure>
            <p>&ldquo;A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.&rdquo;</p>
            <p class="probootstrap-quote-author"><img src="{{ url_for('static', filename='img/person_1.jpg') }}" alt="Free Bootstrap Template by ProBootstrap.com"> Chris Worth, Uber</p>
          </blockquote>
        </div>
      </div>
    </div>
  </section>
  <!-- END: section -->

  <!-- START: section -->
  <section class="probootstrap-section probootstrap-section-extra">
    <div class="container-fluid probootstrap-absolute">
      <div class="row">
        <div class="col-md-8 col-md-pull-2 probootstrap-animate" data-animate-effect="fadeInLeft">
          <img src="{{ url_for('static',filename='img/laptop_1.jpg') }}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-md-5 col-md-push-6 section-heading probootstrap-animate">
          <h2>We design extraordinary</h2>
          <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
          <blockquote class="probootstrap-quote">
            <figure class="probootstrap-quote-logo facebook">
             <img src="{{ url_for('static',filename='img/facebook.png') }}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive">
            </figure>
            <p>&ldquo;A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.&rdquo;</p>
            <p class="probootstrap-quote-author"><img src="{{ url_for('static',filename='img/person_5.jpg') }}" alt="Free Bootstrap Template by ProBootstrap.com"> Janet Morris, Facebook</p>
          </blockquote>
        </div>
      </div>
    </div>
  </section>
  <!-- END: section -->

  <!-- START: section -->
  <section class="probootstrap-section probootstrap-section-extra last">
    <div class="container-fluid probootstrap-absolute">
      <div class="row">
        <div class="col-md-7 col-md-push-6 probootstrap-animate" data-animate-effect="fadeInRight">
          <img src="{{ url_for('static', filename='img/img_showcase_1.jpg') }}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive shadow-left">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-md-5 section-heading probootstrap-animate">
          <h2>We bring emotion to our product</h2>
          <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>

          <blockquote class="probootstrap-quote">
            <figure class="probootstrap-quote-logo twitter">
             <img src="{{ url_for('static',filename='img/twitter.png') }}" alt="Free Bootstrap Template by ProBootstrap.com" class="img-responsive">
            </figure>
            <p>&ldquo;A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.&rdquo;</p>
            <p class="probootstrap-quote-author"><img src="{{ url_for('static',filename='img/person_7.jpg')}}" alt="Free Bootstrap Template by ProBootstrap.com"> Jessa Sy, Twitter</p>
          </blockquote>
        </div>
      </div>
    </div>
  </section>
  <!-- END: section -->
  <!-- START: section -->
  <section class="probootstrap-section probootstrap-section-colored">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 section-heading mb50 text-center probootstrap-animate">
          <h2>More Benefits</h2>
          <p class="lead">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <h3 class="heading-with-icon"><i class="icon-heart2"></i> <span>We bring emotion</span></h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <h3 class="heading-with-icon"><i class="icon-rocket"></i> <span>We guide companies</span></h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <h3 class="heading-with-icon"><i class="icon-image"></i> <span>We design extraordinary</span></h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
        </div>
        <div class="clearfix visible-md-block"></div>
        <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <h3 class="heading-with-icon"><i class="icon-briefcase"></i> <span>We bring emotion</span></h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <h3 class="heading-with-icon"><i class="icon-chat"></i> <span>We guide companies</span></h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <h3 class="heading-with-icon"><i class="icon-colours"></i> <span>We design extraordinary</span></h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
        </div>
        <div class="clearfix visible-sm-block"></div>
      </div>
    </div>
  </section>
  <!-- END: section -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 section-heading mb50 text-center">
          <h2>Our Products</h2>
          <p class="lead">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12">
          <h3 class="mb30">We bring emotion</h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
          <p><a href="#" class="link-with-icon">Learn More <i class=" icon-chevron-right"></i></a></p>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">
          <h3 class="mb30">We guide companies</h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
          <p><a href="#" class="link-with-icon">Learn More <i class=" icon-chevron-right"></i></a></p>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">
          <h3 class="mb30">We design extraordinary</h3>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
          <p><a href="#" class="link-with-icon">Learn More <i class=" icon-chevron-right"></i></a></p>
        </div>
      </div>
    </div>
  </section>
  <!-- END: section -->
{% endblock %}

app/templates/partials/scripts.html
    <script src="{{ url_for('static', filename='js/scripts.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/custom.js') }}"></script>

app/templates/partials/styles.html
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles-merged.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">

    <!--[if lt IE 9]>
      <script src="{{ url_for('static', filename='js/vendor/html5shiv.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/vendor/respond.min.js') }}"></script>
    <![endif]-->